### ISSUE TITLE
how to take a photo ?

### ISSUE THREAD

**Issue by muafakul** [WeLikeVis/CameraFilter#3]
how to take a photo ,,using button?

**Comment by nekocode** [comment]
I had not implemented it. This is just a demo to show how to use shader to implement some filters.

**Comment by johan-schoeman** [comment]
Can you please add the code to take a photo?

**Comment by nekocode** [comment]
@johan-schoeman It is not a hard work. Ok, I will add it quickly.

**Comment by johan-schoeman** [comment]
That will be great! Thanks a lot - really appreciate it!

**Comment by nekocode** [comment]
@muafakul @johan-schoeman  Take a look at the lastest [1.5 version](https://github.com/WeLikeVis/CameraFilter/releases/tag/1.5). I have added new feature to caputre the image.

**Comment by johan-schoeman** [comment]
Thank you very much! Will test it a bit later today and will let you know.

**Comment by nekocode** [comment]
I have not optimize it because I am now focusing more on the 2.0 version development. So please keep the issue open util I finished the optimization.
