### ISSUE TITLE
APK files in releases show wrong version number

### ISSUE THREAD

**Issue by IzzySoft** [WeLikeVis/CameraFilter#4]
For the 1.4 release, the APK still shows 1.4:

    package: name='cn.nekocode.camerafilter' versionCode='1' versionName='1.0'

Could you please upload a fixed version, and keep numbers in sync? Thanks in advance!

**Comment by nekocode** [comment]
Yes, I will fix them in the next version. Thanks for your suggestion.

**Comment by IzzySoft** [comment]
Thanks a lot! Please let me know then (I'll leave this issue open for that purpose). I'd really like to include your app with [my repo](https://android.izzysoft.de/repo), if that's OK with you :)

**Comment by nekocode** [comment]
Yes, of course that's OK. I have already fixed it just now, you can take a look at the [1.5 version](https://github.com/WeLikeVis/CameraFilter/releases/tag/1.5).

**Comment by IzzySoft** [comment]
Thanks a lot! [Here you go](https://android.izzysoft.de/repo/apk/cn.nekocode.camerafilter) ;) Maybe you also want to add some license information – if you already chose a license, that is?

PS: If you want me to add/change something to the description, let me know. I basically copied the details from the `README.md` of the project.

**Comment by nekocode** [comment]
Thanks for your reminder, I had already declared the license for this project at the top of [README.md](https://github.com/WeLikeVis/CameraFilter/blob/master/README.md) (see the badge).

**Comment by IzzySoft** [comment]
Ouch :see_no_evil: Sorry, sure. I was looking for some `License.*` file. As those badges at that position in most cases show results from build processes etc, I've started ignoring them...

Thanks again!

**Comment by IzzySoft** [comment]
Um, it just happened again: v2.1.1 and v2.2 have the same versionCode:

    package: name='cn.nekocode.camerafilter' versionCode='211' versionName='2.1.1' platformBuildVersionName='6.0-2704002'
    package: name='cn.nekocode.camerafilter' versionCode='211' versionName='2.2' platformBuildVersionName=''

To not have my repo stuck, I've removed v2.1.1 manually. Please ensure to update both, versionCode and versionName when releasing a new version :)

**Comment by nekocode** [comment]
@IzzySoft Ok, I will remember it ~
